JSON morgue
crawl/crawl pull request #1122
Opened 2019-07-26 13:05 UTC by giann

It needs a some amount of testing but here's a first draft of JSON morgue files.
They are generated along the normal txt morgue.

To have an idea of the whole JSON structure look at `crawl-ref/source/dat/MorgueSchema.json`

2019-09-30 12:54 UTC, alexjurkiewicz commented
This looks really cool! How do JSON morgue sizes compare to text format?

2019-09-30 18:20 UTC, giann commented
It can vary greatly with the length of the game but I'd say up to 5 times the text format. It depends also of were we put the limit between how much stuff we want to describe/incorporate for potential clients to use.

2019-09-30 19:59 UTC, alexjurkiewicz commented
For server owners it is probably fine, but if this is merged they'll need
to get a heads up with instructions on how to disable it (-extra-opt-last
json_morgues=false or something I guess)

On Tue, 1 Oct 2019, 4:20 am Benoit Giannangeli, <notifications@github.com>
wrote:

> It can vary greatly with the length of the game but I'd say up to 5 times
> the text format. It depends also of were we put the limit between how much
> stuff we want to describe/incorporate for potential clients to use.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/crawl/crawl/pull/1122?email_source=notifications&email_token=AAC4U5ON6PJ6LDD3SHE3RQTQMI7QJA5CNFSM4IHDUZS2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD76TFEQ#issuecomment-536687250>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAC4U5IVCYVDF5MS7IBS47LQMI7QJANCNFSM4IHDUZSQ>
> .
>

2019-10-01 06:33 UTC, aidanholm commented on crawl-ref/source/chardump.cc
> +        json_append_member(header, "seed", json_mknumber(crawl_state.seed));
This should be stored as a string, otherwise large seeds could lose precision when stored as a floating point number.

2020-07-16 14:46 UTC, giann commented
Hey there @ebering. I think some discussion is needed to decide where to put the threshold on what should be in a json morgue file or not. I started alongside a web viewer for it and was finding myself adding more and more stuff in it so I could do more in the viewer. Nonetheless I think there should be more information in a json morgue vs a txt morgue because the end user will most likely not be a human and this allows for more data.

This PR is quite old so I'm not sure about the state of it. I'll try and work on it again if there's a drive for it coming from the dev team.

2020-07-20 13:33 UTC, ebering commented
@giann I'll say now that yes there's a drive for this coming from the devteam. We have in the past used morgue sections to collect data about typical games, but dealing with the plain text morgues is always a bit of a struggle. Having a JSON morgue format would greatly improve this sort of metric collection. You'll see a merge conflict now because we adjusted one of these diagnostics and turned it on again by default. I think that otherwise the patch should apply cleanly; the only outstanding issue is the web server option with a default to off, allowing our server admins to make the decision on their own.

From that point of view a "more data is better" approach is very much the one to take for the JSON morgue, so implementing every optional morgue section as a part of the json morgue is greatly appreciated, but what you have now looks like a lot and working so don't feel the need to add more pre-merge, you can always send more PRs.

2020-07-20 13:36 UTC, giann commented
Alright I’ll implement the option and test things out again.

2020-07-29 12:55 UTC, giann commented
stupid me the option should not be something the players can modify via rc file... ignore f82fdcf please

2020-09-07 08:11 UTC, giann commented
@ebering ping?

2020-09-07 12:33 UTC, ebering commented
@giann Sorry I haven't been able to take a look at this since your last ping. I'm preparing for an international move and don't have much crawl time. It's on my list, and I've added the 0.26 milestone so it doesn't get forgotten!

2020-09-11 23:07 UTC, ebering requested changes
I've read through the schema and given some general feedback on the types and structure. The two big themes are: number versus string in various places and a desire for some deduplication when compared to the text Morgue.

I'm not sure how possible this is, so it's not a condition of merging, but it would be nice to add a test in our test apparatus that creates a character and kills it and verifies that the generated json for the morgue validates against the schema.

In terms of letting server operators know they can disable it with their server configurations we've got better infrastructure for communicating with operators than we had when this patch was first submitted, so I don't expect that to be an issue, especially with it starting as an option defaulting to false.

I've held off on a more nitty-gritty code review of the implementation because at-a-glance it looks good, it is sure to change in response to the schema review, and you've been waiting a while for an updated and I'm almost out of crawl time for this evening. Thank you for your patience, this is something we are interested in!

2020-09-13 10:17 UTC, giann commented on crawl-ref/source/dat/MorgueSchema.json
> +                    "type": "string"
auts?

2020-09-21 13:37 UTC, aidanholm commented on crawl-ref/source/dat/MorgueSchema.json
> +                    "type": "string"
Arbitrary Units of Time

2022-12-09 22:05 UTC, rawlins commented
Still a very cool PR but this is now a year+ stale, I wonder if this should be closed (which definitely wouldn't preclude it getting resurrected)? Just reading back quickly I don't have a great sense for what would need to be done for it to be merged.

2024-06-27 12:15 UTC, giann commented
Unlikely I'll ever pick this up again now. Closing.

2024-06-27 12:15 UTC, closed without merging