Nerf the warlock's mirror & improve debugging messages
crawl/crawl pull request #1839
Opened 2021-03-20 14:26 UTC by Aliscans

Add a debug statement to give the odds of blocking an AUTOMATIC_HIT bolt with the warlock's mirror.

Reduce the chance to block AUTOMATIC_HIT bolts with a displayed SH of 20 from 2/3 to 1/2.

2021-03-21 08:47 UTC, ebering commented
What is the reason for the gameplay change? The Warlocks mirror isn't well renowned as an overly strong unrand...

2021-03-21 14:28 UTC, Aliscans commented
As it was, a comment in bolt::misses_player() said it gave a 50% chance of reflecting AUTOMATIC_HIT attacks at 20 SH, but the code gave a 50% chance of reflecting them at 10 SH.  While the warlock's mirror seems to have changed quite a lot in power over the years, I can't see anything in the log to suggest that anyone wanted it to reflect AUTOMATIC_HIT things more often.

I only chose to change the code because it seemed more in keeping with the intention behind the artefact. I'd be just as happy if the comment was changed to describe what the shield actually does.

2021-03-22 07:08 UTC, ebering requested changes
Yes, correcting the comment is preferred to nerfing the item.

2021-03-23 07:04 UTC, ebering approved these changes

2021-03-23 07:05 UTC, merged