feat: Ball lightning trails
crawl/crawl pull request #2809
Opened 2022-11-02 15:33 UTC by scarf005

![Dungeon Crawl Stone Soup 0 30-a0-341-g68270651_01](https://user-images.githubusercontent.com/54838975/199532104-e64b6d0e-a72c-4460-a7a0-a54a3d5162ee.png) 
![Dungeon Crawl Stone Soup 0 30-a0-341-g68270651_02](https://user-images.githubusercontent.com/54838975/199532110-08487d84-8a76-4945-948d-2a5e33868309.png)

make ball lightnings leave harmless trail (similar to foxfire trail), because it's pretty.

2023-01-07 06:11 UTC, PleasingFungus requested changes
This is very cool! Many apologies for the long delay in review.

2023-01-07 06:11 UTC, PleasingFungus commented on crawl-ref/source/cloud-type.h
> +    CLOUD_ELECTRICITY,
Inserting an enum into the middle of a list of enums will break save compatibility if the enum is marshalled (included in save files), as this one is. Anyone who loads up an old save after this change will find all degeneration clouds have turned into electricity clouds, and all blastsparks turned into degeneration.

You need to insert this at the end of the enum, right before NUM_CLOUD_TYPES.

2023-01-07 06:11 UTC, PleasingFungus commented on crawl-ref/source/cloud.cc
> +    { "wisps of electric spark", nullptr,         // terse, verbose name
"wisps of electric spark" isn't quite valid English. I'd recommend just 'sparks'.

2023-01-07 06:11 UTC, PleasingFungus commented on crawl-ref/source/cloud.cc
> +    // CLOUD_ELECTRICITY,
The new cloud needs an entry in `dat/descript/clouds.txt`.

2023-01-10 08:14 UTC, scarf005 commented
closing in order to reopen PR (#2925) from another fork.

2023-01-10 08:15 UTC, closed without merging