Fix the MSVC build
crawl/crawl pull request #3647
Opened 2024-03-11 07:45 UTC by WizardIke

2024-03-11 18:06 UTC, pooka109 commented
I've gone ahead and incorporated the mon-death.cc fix from this, in 100c63a273397be46af4daa6c58765d76d52cca7.

(I don't use MSVC or even Windows, but there's no way using "and" instead of "&&" there should have compiled at all, regardless.)

2024-03-18 04:33 UTC, PleasingFungus commented
Thanks for working on this! This touches enough files that it'll take some time to review (and I haven't started on review), but I'm hopeful that it can land.

It'd be ideal if a Windows user could review this. I'm not sure how many of those we have.

2025-02-02 21:04 UTC, wheals requested changes
Great work, I decided to test this out and only ran into some minor issues.

I also noticed a whole bunch of warnings by MSVC but I can take care of those myself in later commits.

2025-02-02 21:04 UTC, wheals commented on crawl-ref/source/contrib/MSVC/libpng.vcxproj
MSVC was initially unable to build this contrib properly because it couldn't find `zlib.lib`. I fixed this issue by changing the linker's `AdditionalLibraryDirectories` to `$(TargetDir)`. I had to do this for both debug and release configs.

2025-02-04 10:07 UTC, WizardIke commented on crawl-ref/INSTALL.md
> +This build is tested on Visual Studio 2017 15.9.60 on Windows 11.
Thanks, I've added that it has been tested on windows 10 to INSTALL.md

2025-02-04 10:13 UTC, WizardIke commented on crawl-ref/INSTALL.md
>  - Make sure all projects use `/MD` (or `/MDd` for the debug version)
I've replaced the references to building the `Contribs` solution

2025-02-04 10:32 UTC, WizardIke commented on crawl-ref/source/util/gen-all.py
> +    inputs_last_modified = get_max_file_modified_time(input_files)
Missing input files should throw an exception that stops gen-all from running. However, I probably should catch the exception and format it in a way that Visual Studio understands so the build fails properly.

2025-02-04 11:28 UTC, WizardIke commented on crawl-ref/source/util/gen-all.py
> +    inputs_last_modified = get_max_file_modified_time(input_files)
The build was failing when an input file was missing already. However, the error message wasn't readable. The message is now readable and shows up in Visual Studio's error list.

2025-02-05 04:06 UTC, WizardIke commented on crawl-ref/INSTALL.md
It seems to have never existed or at least didn't exist when the reference to it was added in commit fe06877 either way I've removed the reference to it.

2025-02-05 07:38 UTC, WizardIke commented on crawl-ref/source/util/gen-all.py
I've moved generation of the tile info into gen-all.py to that it happens after `dc-unrand.txt` is generated

2025-02-05 08:10 UTC, WizardIke commented on crawl-ref/source/contrib/MSVC/libpng.vcxproj
Thanks for the fix

2025-02-05 09:42 UTC, wheals approved these changes

2025-02-05 09:51 UTC, merged